# Generated by Django 3.2.5 on 2021-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
